///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SignupResponseData {
/*
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTA2NjhkOTViZTM4MTgwYWY3NGQzOTQ1YWZiNmQ1YjEwYzhkYzNhYjgwODgzN2M3YTBhODk4NWZjNzhjOTc4Mjc0YzZlOTFjMjNiZTVhZTQiLCJpYXQiOjE2MzAwNDU0MDcsIm5iZiI6MTYzMDA0NTQwNywiZXhwIjoxNjYxNTgxNDA3LCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.kdAsveT7-fpWNPUEPyRQTsIaE3gcmCCuaKE81-VwVj-zpJv28WxHuOJpM-xAAIbwMqValMGofXoat8GJZCYNbSNdCtlpZMVWPWZ2e7f0CnKLMxiAPeNSrmJNNcSpRVY9dUeoJRGqgkWcNKcWOwDjxjQ6qnHZZQKZLx8dcUMUK2YVPMCTH9_cNtZu39XuO-8Bo6mrs9DAbeP3UsFYH9vXdYSrVDLCzqqi2kUGGJmVRMBKdcnKg_kDICOWk3R-RXhm4GUKxS3H4nAxWpgJ-Oe8PSXNiAAkFvJvNjhmIsncZlAwxGyZvhZzgGN_xIC8Q7o_8rl4w-wKPMouGyaQFTGYQAITz9fJkfj68OY9t6hD-E3xDofDLFCLU0hF6aU_J7mKdOIIYCF0Zf4fJ0gZg9iR86dD_EwuIcISZttPzwJFA0nmwFl6OaKob8eDIK7tMKSRyelEeRMx8_5LFgZ0ivC1Pfhu_qmY8oSOA4SuaohO-xEZdcJukWX7wNbY_naoMYOoC7bvurpzVz1nLx0zzDnq5JXJZF35X6XYiETIFkm9Bx7dR06k8BJls4NFMY2NhGkdTVQGF6XiaI93MCAEQCnwxoKEsJDQVfgIwkEKn0vcL06J5fj9eZIvMCNhHv_1G8UIo1NeobRnX0rg6-xVtCo2f2GGqDkpGRHczXwi4D8R7R4",
  "name": "jayesh",
  "status": 0,
  "user_id": 0
}
*/

  String? token;
  String? name;
  int? status;
  int? userId;

  SignupResponseData({
    this.token,
    this.name,
    this.status,
    this.userId,
  });
  SignupResponseData.fromJson(Map<String, dynamic> json) {
    token = json["token"]?.toString();
    name = json["name"]?.toString();
    status = json["status"]?.toInt();
    userId = json["user_id"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["token"] = token;
    data["name"] = name;
    data["status"] = status;
    data["user_id"] = userId;
    return data;
  }
}

class SignupResponse {
/*
{
  "success": true,
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTA2NjhkOTViZTM4MTgwYWY3NGQzOTQ1YWZiNmQ1YjEwYzhkYzNhYjgwODgzN2M3YTBhODk4NWZjNzhjOTc4Mjc0YzZlOTFjMjNiZTVhZTQiLCJpYXQiOjE2MzAwNDU0MDcsIm5iZiI6MTYzMDA0NTQwNywiZXhwIjoxNjYxNTgxNDA3LCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.kdAsveT7-fpWNPUEPyRQTsIaE3gcmCCuaKE81-VwVj-zpJv28WxHuOJpM-xAAIbwMqValMGofXoat8GJZCYNbSNdCtlpZMVWPWZ2e7f0CnKLMxiAPeNSrmJNNcSpRVY9dUeoJRGqgkWcNKcWOwDjxjQ6qnHZZQKZLx8dcUMUK2YVPMCTH9_cNtZu39XuO-8Bo6mrs9DAbeP3UsFYH9vXdYSrVDLCzqqi2kUGGJmVRMBKdcnKg_kDICOWk3R-RXhm4GUKxS3H4nAxWpgJ-Oe8PSXNiAAkFvJvNjhmIsncZlAwxGyZvhZzgGN_xIC8Q7o_8rl4w-wKPMouGyaQFTGYQAITz9fJkfj68OY9t6hD-E3xDofDLFCLU0hF6aU_J7mKdOIIYCF0Zf4fJ0gZg9iR86dD_EwuIcISZttPzwJFA0nmwFl6OaKob8eDIK7tMKSRyelEeRMx8_5LFgZ0ivC1Pfhu_qmY8oSOA4SuaohO-xEZdcJukWX7wNbY_naoMYOoC7bvurpzVz1nLx0zzDnq5JXJZF35X6XYiETIFkm9Bx7dR06k8BJls4NFMY2NhGkdTVQGF6XiaI93MCAEQCnwxoKEsJDQVfgIwkEKn0vcL06J5fj9eZIvMCNhHv_1G8UIo1NeobRnX0rg6-xVtCo2f2GGqDkpGRHczXwi4D8R7R4",
    "name": "jayesh",
    "status": 0,
    "user_id": 0
  },
  "message": "Login successfully."
}
*/

  bool? success;
  SignupResponseData? data;
  String? message;

  SignupResponse({
    this.success,
    this.data,
    this.message,
  });
  SignupResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? SignupResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
