///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SignupFailResponseData {
/*
{
  "mobile_number": [
    "The mobile number has already been taken."
  ]
}
*/

  List<String?>? mobileNumber;

  SignupFailResponseData({
    this.mobileNumber,
  });
  SignupFailResponseData.fromJson(Map<String, dynamic> json) {
    if (json["mobile_number"] != null) {
      final v = json["mobile_number"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      mobileNumber = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (mobileNumber != null) {
      final v = mobileNumber;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["mobile_number"] = arr0;
    }
    return data;
  }
}

class SignupFailResponse {
/*
{
  "success": false,
  "message": "Validation Error.",
  "data": {
    "mobile_number": [
      "The mobile number has already been taken."
    ]
  }
}
*/

  bool? success;
  String? message;
  SignupFailResponseData? data;

  SignupFailResponse({
    this.success,
    this.message,
    this.data,
  });
  SignupFailResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    message = json["message"]?.toString();
    data = (json["data"] != null) ? SignupFailResponseData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}
