///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressListResponseDataAddress {
/*
{
  "id": 2,
  "user_id": 2,
  "country_id": 1,
  "state_id": 1,
  "city_id": 1,
  "name": "jayesh",
  "mobile": "7304610113",
  "land_mark": "near school",
  "address": "icici bank",
  "pincode": "411021",
  "latitude": "412131",
  "longitude": "342332",
  "status": true,
  "created_at": "2021-08-28T07:47:48.000000Z",
  "updated_at": "2021-08-28T07:47:48.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  int? countryId;
  int? stateId;
  int? cityId;
  String? name;
  String? mobile;
  String? landMark;
  String? address;
  String? pincode;
  String? latitude;
  String? longitude;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AddressListResponseDataAddress({
    this.id,
    this.userId,
    this.countryId,
    this.stateId,
    this.cityId,
    this.name,
    this.mobile,
    this.landMark,
    this.address,
    this.pincode,
    this.latitude,
    this.longitude,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  AddressListResponseDataAddress.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    countryId = json["country_id"]?.toInt();
    stateId = json["state_id"]?.toInt();
    cityId = json["city_id"]?.toInt();
    name = json["name"]?.toString();
    mobile = json["mobile"]?.toString();
    landMark = json["land_mark"]?.toString();
    address = json["address"]?.toString();
    pincode = json["pincode"]?.toString();
    latitude = json["latitude"]?.toString();
    longitude = json["longitude"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["country_id"] = countryId;
    data["state_id"] = stateId;
    data["city_id"] = cityId;
    data["name"] = name;
    data["mobile"] = mobile;
    data["land_mark"] = landMark;
    data["address"] = address;
    data["pincode"] = pincode;
    data["latitude"] = latitude;
    data["longitude"] = longitude;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class AddressListResponseData {
/*
{
  "address": [
    {
      "id": 2,
      "user_id": 2,
      "country_id": 1,
      "state_id": 1,
      "city_id": 1,
      "name": "jayesh",
      "mobile": "7304610113",
      "land_mark": "near school",
      "address": "icici bank",
      "pincode": "411021",
      "latitude": "412131",
      "longitude": "342332",
      "status": true,
      "created_at": "2021-08-28T07:47:48.000000Z",
      "updated_at": "2021-08-28T07:47:48.000000Z",
      "deleted_at": null
    }
  ]
}
*/

  List<AddressListResponseDataAddress?>? address;

  AddressListResponseData({
    this.address,
  });
  AddressListResponseData.fromJson(Map<String, dynamic> json) {
    if (json["address"] != null) {
      final v = json["address"];
      final arr0 = <AddressListResponseDataAddress>[];
      v.forEach((v) {
        arr0.add(AddressListResponseDataAddress.fromJson(v));
      });
      address = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (address != null) {
      final v = address;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["address"] = arr0;
    }
    return data;
  }
}

class AddressListResponse {
/*
{
  "success": true,
  "data": {
    "address": [
      {
        "id": 2,
        "user_id": 2,
        "country_id": 1,
        "state_id": 1,
        "city_id": 1,
        "name": "jayesh",
        "mobile": "7304610113",
        "land_mark": "near school",
        "address": "icici bank",
        "pincode": "411021",
        "latitude": "412131",
        "longitude": "342332",
        "status": true,
        "created_at": "2021-08-28T07:47:48.000000Z",
        "updated_at": "2021-08-28T07:47:48.000000Z",
        "deleted_at": null
      }
    ]
  },
  "message": "address list."
}
*/

  bool? success;
  AddressListResponseData? data;
  String? message;

  AddressListResponse({
    this.success,
    this.data,
    this.message,
  });
  AddressListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? AddressListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["data"] = this.data!.toJson();
    data["message"] = message;
    return data;
  }
}
