///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CityListResponseDataCity {
/*
{
  "id": 1,
  "country_id": 1,
  "state_id": 1,
  "name": "yavatmal",
  "code": "44",
  "status": true,
  "created_at": "2021-08-31T20:01:52.000000Z",
  "updated_at": null,
  "deleted_at": null
}
*/

  int? id;
  int? countryId;
  int? stateId;
  String? name;
  String? code;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  CityListResponseDataCity({
    this.id,
    this.countryId,
    this.stateId,
    this.name,
    this.code,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  CityListResponseDataCity.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    countryId = json["country_id"]?.toInt();
    stateId = json["state_id"]?.toInt();
    name = json["name"]?.toString();
    code = json["code"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["country_id"] = countryId;
    data["state_id"] = stateId;
    data["name"] = name;
    data["code"] = code;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class CityListResponseData {
/*
{
  "city": [
    {
      "id": 1,
      "country_id": 1,
      "state_id": 1,
      "name": "yavatmal",
      "code": "44",
      "status": true,
      "created_at": "2021-08-31T20:01:52.000000Z",
      "updated_at": null,
      "deleted_at": null
    }
  ]
}
*/

  List<CityListResponseDataCity?>? city;

  CityListResponseData({
    this.city,
  });
  CityListResponseData.fromJson(Map<String, dynamic> json) {
    if (json["city"] != null) {
      final v = json["city"];
      final arr0 = <CityListResponseDataCity>[];
      v.forEach((v) {
        arr0.add(CityListResponseDataCity.fromJson(v));
      });
      city = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (city != null) {
      final v = city;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["city"] = arr0;
    }
    return data;
  }
}

class CityListResponse {
/*
{
  "success": true,
  "data": {
    "city": [
      {
        "id": 1,
        "country_id": 1,
        "state_id": 1,
        "name": "yavatmal",
        "code": "44",
        "status": true,
        "created_at": "2021-08-31T20:01:52.000000Z",
        "updated_at": null,
        "deleted_at": null
      }
    ]
  },
  "message": "City list."
}
*/

  bool? success;
  CityListResponseData? data;
  String? message;

  CityListResponse({
    this.success,
    this.data,
    this.message,
  });
  CityListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? CityListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
