///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PincodeListResponseDataPincode {
/*
{
  "id": 1,
  "pincode": 445002,
  "status": true,
  "created_at": "2021-08-31T20:02:42.000000Z",
  "updated_at": null,
  "deleted_at": null
}
*/

  int? id;
  int? pincode;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  PincodeListResponseDataPincode({
    this.id,
    this.pincode,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  PincodeListResponseDataPincode.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    pincode = json["pincode"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["pincode"] = pincode;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class PincodeListResponseData {
/*
{
  "pincode": [
    {
      "id": 1,
      "pincode": 445002,
      "status": true,
      "created_at": "2021-08-31T20:02:42.000000Z",
      "updated_at": null,
      "deleted_at": null
    }
  ]
}
*/

  List<PincodeListResponseDataPincode?>? pincode;

  PincodeListResponseData({
    this.pincode,
  });
  PincodeListResponseData.fromJson(Map<String, dynamic> json) {
    if (json["pincode"] != null) {
      final v = json["pincode"];
      final arr0 = <PincodeListResponseDataPincode>[];
      v.forEach((v) {
        arr0.add(PincodeListResponseDataPincode.fromJson(v));
      });
      pincode = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (pincode != null) {
      final v = pincode;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["pincode"] = arr0;
    }
    return data;
  }
}

class PincodeListResponse {
/*
{
  "success": true,
  "data": {
    "pincode": [
      {
        "id": 1,
        "pincode": 445002,
        "status": true,
        "created_at": "2021-08-31T20:02:42.000000Z",
        "updated_at": null,
        "deleted_at": null
      }
    ]
  },
  "message": "pincode list."
}
*/

  bool? success;
  PincodeListResponseData? data;
  String? message;

  PincodeListResponse({
    this.success,
    this.data,
    this.message,
  });
  PincodeListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? PincodeListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
