///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WishUpdateResponseDataWishProduct {
/*
{
  "id": 5,
  "user_id": 1,
  "category_id": 1,
  "sub_category_id": 1,
  "store_id": 1,
  "name": "beetroot",
  "weight": "2",
  "price": "22.00",
  "s_price": "22.00",
  "m_o_quantity": 2,
  "p_image": "public/admin/product/image/beetroot.jpg",
  "sku": "sku002222",
  "unit": "kg",
  "description": "<p><span style=\"color: rgb(77, 81, 86); font-family: arial, sans-serif;\">Pyrus pyrifolia is a species of pear tree native to East Asia. The tree's edible fruit is known by many names, including: Asian pear, Japanese pear, Chinese pear, Korean pear, Taiwanese pear, apple pear, zodiac pear, three-halves pear, papple, Naspati and sand</span><br></p>",
  "sort_order": 22,
  "stock": 1,
  "status": true,
  "offer": 0,
  "created_at": "2021-08-25T06:30:31.000000Z",
  "updated_at": "2021-08-27T11:08:06.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  int? categoryId;
  int? subCategoryId;
  int? storeId;
  String? name;
  String? weight;
  String? price;
  String? sPrice;
  int? mOQuantity;
  String? pImage;
  String? sku;
  String? unit;
  String? description;
  int? sortOrder;
  int? stock;
  bool? status;
  int? offer;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  WishUpdateResponseDataWishProduct({
    this.id,
    this.userId,
    this.categoryId,
    this.subCategoryId,
    this.storeId,
    this.name,
    this.weight,
    this.price,
    this.sPrice,
    this.mOQuantity,
    this.pImage,
    this.sku,
    this.unit,
    this.description,
    this.sortOrder,
    this.stock,
    this.status,
    this.offer,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  WishUpdateResponseDataWishProduct.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    categoryId = json["category_id"]?.toInt();
    subCategoryId = json["sub_category_id"]?.toInt();
    storeId = json["store_id"]?.toInt();
    name = json["name"]?.toString();
    weight = json["weight"]?.toString();
    price = json["price"]?.toString();
    sPrice = json["s_price"]?.toString();
    mOQuantity = json["m_o_quantity"]?.toInt();
    pImage = json["p_image"]?.toString();
    sku = json["sku"]?.toString();
    unit = json["unit"]?.toString();
    description = json["description"]?.toString();
    sortOrder = json["sort_order"]?.toInt();
    stock = json["stock"]?.toInt();
    status = json["status"];
    offer = json["offer"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["category_id"] = categoryId;
    data["sub_category_id"] = subCategoryId;
    data["store_id"] = storeId;
    data["name"] = name;
    data["weight"] = weight;
    data["price"] = price;
    data["s_price"] = sPrice;
    data["m_o_quantity"] = mOQuantity;
    data["p_image"] = pImage;
    data["sku"] = sku;
    data["unit"] = unit;
    data["description"] = description;
    data["sort_order"] = sortOrder;
    data["stock"] = stock;
    data["status"] = status;
    data["offer"] = offer;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class WishUpdateResponseDataWish {
/*
{
  "id": 2,
  "user_id": 2,
  "product_id": 5,
  "status": 1,
  "created_at": "2021-08-31T07:04:32.000000Z",
  "updated_at": "2021-08-31T07:04:32.000000Z",
  "deleted_at": null,
  "product": {
    "id": 5,
    "user_id": 1,
    "category_id": 1,
    "sub_category_id": 1,
    "store_id": 1,
    "name": "beetroot",
    "weight": "2",
    "price": "22.00",
    "s_price": "22.00",
    "m_o_quantity": 2,
    "p_image": "public/admin/product/image/beetroot.jpg",
    "sku": "sku002222",
    "unit": "kg",
    "description": "<p><span style=\"color: rgb(77, 81, 86); font-family: arial, sans-serif;\">Pyrus pyrifolia is a species of pear tree native to East Asia. The tree's edible fruit is known by many names, including: Asian pear, Japanese pear, Chinese pear, Korean pear, Taiwanese pear, apple pear, zodiac pear, three-halves pear, papple, Naspati and sand</span><br></p>",
    "sort_order": 22,
    "stock": 1,
    "status": true,
    "offer": 0,
    "created_at": "2021-08-25T06:30:31.000000Z",
    "updated_at": "2021-08-27T11:08:06.000000Z",
    "deleted_at": null
  }
}
*/

  int? id;
  int? userId;
  int? productId;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  WishUpdateResponseDataWishProduct? product;

  WishUpdateResponseDataWish({
    this.id,
    this.userId,
    this.productId,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.product,
  });
  WishUpdateResponseDataWish.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    productId = json["product_id"]?.toInt();
    status = json["status"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    product = (json["product"] != null) ? WishUpdateResponseDataWishProduct.fromJson(json["product"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["product_id"] = productId;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    if (product != null) {
      data["product"] = product!.toJson();
    }
    return data;
  }
}

class WishUpdateResponseData {
/*
{
  "wish": [
    {
      "id": 2,
      "user_id": 2,
      "product_id": 5,
      "status": 1,
      "created_at": "2021-08-31T07:04:32.000000Z",
      "updated_at": "2021-08-31T07:04:32.000000Z",
      "deleted_at": null,
      "product": {
        "id": 5,
        "user_id": 1,
        "category_id": 1,
        "sub_category_id": 1,
        "store_id": 1,
        "name": "beetroot",
        "weight": "2",
        "price": "22.00",
        "s_price": "22.00",
        "m_o_quantity": 2,
        "p_image": "public/admin/product/image/beetroot.jpg",
        "sku": "sku002222",
        "unit": "kg",
        "description": "<p><span style=\"color: rgb(77, 81, 86); font-family: arial, sans-serif;\">Pyrus pyrifolia is a species of pear tree native to East Asia. The tree's edible fruit is known by many names, including: Asian pear, Japanese pear, Chinese pear, Korean pear, Taiwanese pear, apple pear, zodiac pear, three-halves pear, papple, Naspati and sand</span><br></p>",
        "sort_order": 22,
        "stock": 1,
        "status": true,
        "offer": 0,
        "created_at": "2021-08-25T06:30:31.000000Z",
        "updated_at": "2021-08-27T11:08:06.000000Z",
        "deleted_at": null
      }
    }
  ]
}
*/

  List<WishUpdateResponseDataWish?>? wish;

  WishUpdateResponseData({
    this.wish,
  });
  WishUpdateResponseData.fromJson(Map<String, dynamic> json) {
    if (json["wish"] != null) {
      final v = json["wish"];
      final arr0 = <WishUpdateResponseDataWish>[];
      v.forEach((v) {
        arr0.add(WishUpdateResponseDataWish.fromJson(v));
      });
      wish = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (wish != null) {
      final v = wish;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["wish"] = arr0;
    }
    return data;
  }
}

class WishUpdateResponse {
/*
{
  "success": true,
  "data": {
    "wish": [
      {
        "id": 2,
        "user_id": 2,
        "product_id": 5,
        "status": 1,
        "created_at": "2021-08-31T07:04:32.000000Z",
        "updated_at": "2021-08-31T07:04:32.000000Z",
        "deleted_at": null,
        "product": {
          "id": 5,
          "user_id": 1,
          "category_id": 1,
          "sub_category_id": 1,
          "store_id": 1,
          "name": "beetroot",
          "weight": "2",
          "price": "22.00",
          "s_price": "22.00",
          "m_o_quantity": 2,
          "p_image": "public/admin/product/image/beetroot.jpg",
          "sku": "sku002222",
          "unit": "kg",
          "description": "<p><span style=\"color: rgb(77, 81, 86); font-family: arial, sans-serif;\">Pyrus pyrifolia is a species of pear tree native to East Asia. The tree's edible fruit is known by many names, including: Asian pear, Japanese pear, Chinese pear, Korean pear, Taiwanese pear, apple pear, zodiac pear, three-halves pear, papple, Naspati and sand</span><br></p>",
          "sort_order": 22,
          "stock": 1,
          "status": true,
          "offer": 0,
          "created_at": "2021-08-25T06:30:31.000000Z",
          "updated_at": "2021-08-27T11:08:06.000000Z",
          "deleted_at": null
        }
      }
    ]
  },
  "message": "Wish list."
}
*/

  bool? success;
  WishUpdateResponseData? data;
  String? message;

  WishUpdateResponse({
    this.success,
    this.data,
    this.message,
  });
  WishUpdateResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? WishUpdateResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
