///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WishCartAddResponseData {
/*
{
  "card_id": 0
}
*/

  int? cardId;

  WishCartAddResponseData({
    this.cardId,
  });
  WishCartAddResponseData.fromJson(Map<String, dynamic> json) {
    cardId = json["card_id"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["card_id"] = cardId;
    return data;
  }
}

class WishCartAddResponse {
/*
{
  "success": true,
  "data": {
    "card_id": 0
  },
  "message": " successfully."
}
*/

  bool? success;
  WishCartAddResponseData? data;
  String? message;

  WishCartAddResponse({
    this.success,
    this.data,
    this.message,
  });
  WishCartAddResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? WishCartAddResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
