///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OtpResponse {
/*
{
  "success": true,
  "data": "Successfully Send Otp",
  "message": "User Detail."
}
*/

  bool? success;
  String? data;
  String? message;

  OtpResponse({
    this.success,
    this.data,
    this.message,
  });
  OtpResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = json["data"]?.toString();
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["data"] = this.data;
    data["message"] = message;
    return data;
  }
}
