///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LogoutResponseData {
/*
{
  "data": ""
}
*/

  String? data;

  LogoutResponseData({
    this.data,
  });
  LogoutResponseData.fromJson(Map<String, dynamic> json) {
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["data"] = this.data;
    return data;
  }
}

class LogoutResponse {
/*
{
  "success": true,
  "data": {
    "data": ""
  },
  "message": "logout_success."
}
*/

  bool? success;
  LogoutResponseData? data;
  String? message;

  LogoutResponse({
    this.success,
    this.data,
    this.message,
  });
  LogoutResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? LogoutResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
