///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApplicationSettingResponseDataApplicationSetting {
/*
{
  "id": 1,
  "store_lat": "18.5210",
  "store_long": "73.7741",
  "curent_time": "15:38",
  "curent_date": "2021-10-04",
  "last_date": 10,
  "o_s_timer": "10:00 pm",
  "o_e_timer": "11:00 pm",
  "c_s_timer": "01:00 am",
  "c_e_timer": "03:00 am",
  "minmum_order_weight": "25",
  "d_start": "01:00 am",
  "d_end": "01:00 am",
  "r_pay_key": "rzp_test_g5dAdGUeitPdIi",
  "merchant_payment_id": "MS2109041909257595714573",
  "receiver_name": "Profcyma",
  "receiver_id": "Q545123952@ybl",
  "tag_line": "Ab market dur nahi!",
  "m_o_price": "120",
  "rezor_pay_auth_key": "vXkt2PRkn0Rftb62fjPwKjmf"
}
*/

  int? id;
  String? storeLat;
  String? storeLong;
  String? curentTime;
  String? curentDate;
  int? lastDate;
  String? oSTimer;
  String? oETimer;
  String? cSTimer;
  String? cETimer;
  String? minmumOrderWeight;
  String? dStart;
  String? dEnd;
  String? rPayKey;
  String? merchantPaymentId;
  String? receiverName;
  String? receiverId;
  String? tagLine;
  String? mOPrice;
  String? rezorPayAuthKey;

  ApplicationSettingResponseDataApplicationSetting({
    this.id,
    this.storeLat,
    this.storeLong,
    this.curentTime,
    this.curentDate,
    this.lastDate,
    this.oSTimer,
    this.oETimer,
    this.cSTimer,
    this.cETimer,
    this.minmumOrderWeight,
    this.dStart,
    this.dEnd,
    this.rPayKey,
    this.merchantPaymentId,
    this.receiverName,
    this.receiverId,
    this.tagLine,
    this.mOPrice,
    this.rezorPayAuthKey,
  });
  ApplicationSettingResponseDataApplicationSetting.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    storeLat = json["store_lat"]?.toString();
    storeLong = json["store_long"]?.toString();
    curentTime = json["curent_time"]?.toString();
    curentDate = json["curent_date"]?.toString();
    lastDate = json["last_date"]?.toInt();
    oSTimer = json["o_s_timer"]?.toString();
    oETimer = json["o_e_timer"]?.toString();
    cSTimer = json["c_s_timer"]?.toString();
    cETimer = json["c_e_timer"]?.toString();
    minmumOrderWeight = json["minmum_order_weight"]?.toString();
    dStart = json["d_start"]?.toString();
    dEnd = json["d_end"]?.toString();
    rPayKey = json["r_pay_key"]?.toString();
    merchantPaymentId = json["merchant_payment_id"]?.toString();
    receiverName = json["receiver_name"]?.toString();
    receiverId = json["receiver_id"]?.toString();
    tagLine = json["tag_line"]?.toString();
    mOPrice = json["m_o_price"]?.toString();
    rezorPayAuthKey = json["rezor_pay_auth_key"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["store_lat"] = storeLat;
    data["store_long"] = storeLong;
    data["curent_time"] = curentTime;
    data["curent_date"] = curentDate;
    data["last_date"] = lastDate;
    data["o_s_timer"] = oSTimer;
    data["o_e_timer"] = oETimer;
    data["c_s_timer"] = cSTimer;
    data["c_e_timer"] = cETimer;
    data["minmum_order_weight"] = minmumOrderWeight;
    data["d_start"] = dStart;
    data["d_end"] = dEnd;
    data["r_pay_key"] = rPayKey;
    data["merchant_payment_id"] = merchantPaymentId;
    data["receiver_name"] = receiverName;
    data["receiver_id"] = receiverId;
    data["tag_line"] = tagLine;
    data["m_o_price"] = mOPrice;
    data["rezor_pay_auth_key"] = rezorPayAuthKey;
    return data;
  }
}

class ApplicationSettingResponseData {
/*
{
  "applicationSetting": {
    "id": 1,
    "store_lat": "18.5210",
    "store_long": "73.7741",
    "curent_time": "15:38",
    "curent_date": "2021-10-04",
    "last_date": 10,
    "o_s_timer": "10:00 pm",
    "o_e_timer": "11:00 pm",
    "c_s_timer": "01:00 am",
    "c_e_timer": "03:00 am",
    "minmum_order_weight": "25",
    "d_start": "01:00 am",
    "d_end": "01:00 am",
    "r_pay_key": "rzp_test_g5dAdGUeitPdIi",
    "merchant_payment_id": "MS2109041909257595714573",
    "receiver_name": "Profcyma",
    "receiver_id": "Q545123952@ybl",
    "tag_line": "Ab market dur nahi!",
    "m_o_price": "120",
    "rezor_pay_auth_key": "vXkt2PRkn0Rftb62fjPwKjmf"
  }
}
*/

  ApplicationSettingResponseDataApplicationSetting? applicationSetting;

  ApplicationSettingResponseData({
    this.applicationSetting,
  });
  ApplicationSettingResponseData.fromJson(Map<String, dynamic> json) {
    applicationSetting = (json["applicationSetting"] != null) ? ApplicationSettingResponseDataApplicationSetting.fromJson(json["applicationSetting"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (applicationSetting != null) {
      data["applicationSetting"] = applicationSetting!.toJson();
    }
    return data;
  }
}

class ApplicationSettingResponse {
/*
{
  "success": true,
  "data": {
    "applicationSetting": {
      "id": 1,
      "store_lat": "18.5210",
      "store_long": "73.7741",
      "curent_time": "15:38",
      "curent_date": "2021-10-04",
      "last_date": 10,
      "o_s_timer": "10:00 pm",
      "o_e_timer": "11:00 pm",
      "c_s_timer": "01:00 am",
      "c_e_timer": "03:00 am",
      "minmum_order_weight": "25",
      "d_start": "01:00 am",
      "d_end": "01:00 am",
      "r_pay_key": "rzp_test_g5dAdGUeitPdIi",
      "merchant_payment_id": "MS2109041909257595714573",
      "receiver_name": "Profcyma",
      "receiver_id": "Q545123952@ybl",
      "tag_line": "Ab market dur nahi!",
      "m_o_price": "120",
      "rezor_pay_auth_key": "vXkt2PRkn0Rftb62fjPwKjmf"
    }
  },
  "message": "setting list."
}
*/

  bool? success;
  ApplicationSettingResponseData? data;
  String? message;

  ApplicationSettingResponse({
    this.success,
    this.data,
    this.message,
  });
  ApplicationSettingResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? ApplicationSettingResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
