///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomerSupportResponseDataCustomerSupport {
/*
{
  "id": 1,
  "name": "9718577938",
  "created_at": null,
  "updated_at": null,
  "deleted_at": null
}
*/

  int? id;
  String? name;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  CustomerSupportResponseDataCustomerSupport({
    this.id,
    this.name,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  CustomerSupportResponseDataCustomerSupport.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class CustomerSupportResponseData {
/*
{
  "customerSupport": {
    "id": 1,
    "name": "9718577938",
    "created_at": null,
    "updated_at": null,
    "deleted_at": null
  }
}
*/

  CustomerSupportResponseDataCustomerSupport? customerSupport;

  CustomerSupportResponseData({
    this.customerSupport,
  });
  CustomerSupportResponseData.fromJson(Map<String, dynamic> json) {
    customerSupport = (json["customerSupport"] != null) ? CustomerSupportResponseDataCustomerSupport.fromJson(json["customerSupport"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (customerSupport != null) {
      data["customerSupport"] = customerSupport!.toJson();
    }
    return data;
  }
}

class CustomerSupportResponse {
/*
{
  "success": true,
  "data": {
    "customerSupport": {
      "id": 1,
      "name": "9718577938",
      "created_at": null,
      "updated_at": null,
      "deleted_at": null
    }
  },
  "message": "support list."
}
*/

  bool? success;
  CustomerSupportResponseData? data;
  String? message;

  CustomerSupportResponse({
    this.success,
    this.data,
    this.message,
  });
  CustomerSupportResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? CustomerSupportResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
