///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LanguageListResponseDataLanguage {
/*
{
  "id": 1,
  "name": "English",
  "code": "En",
  "url": "public/admin/product/image/collage-stu.png",
  "status": true,
  "created_at": null,
  "updated_at": null,
  "deleted_at": null
}
*/

  int? id;
  String? name;
  String? code;
  String? url;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  LanguageListResponseDataLanguage({
    this.id,
    this.name,
    this.code,
    this.url,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  LanguageListResponseDataLanguage.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    code = json["code"]?.toString();
    url = json["url"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["code"] = code;
    data["url"] = url;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class LanguageListResponseData {
/*
{
  "language": [
    {
      "id": 1,
      "name": "English",
      "code": "En",
      "url": "public/admin/product/image/collage-stu.png",
      "status": true,
      "created_at": null,
      "updated_at": null,
      "deleted_at": null
    }
  ]
}
*/

  List<LanguageListResponseDataLanguage?>? language;

  LanguageListResponseData({
    this.language,
  });
  LanguageListResponseData.fromJson(Map<String, dynamic> json) {
    if (json["language"] != null) {
      final v = json["language"];
      final arr0 = <LanguageListResponseDataLanguage>[];
      v.forEach((v) {
        arr0.add(LanguageListResponseDataLanguage.fromJson(v));
      });
      language = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (language != null) {
      final v = language;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["language"] = arr0;
    }
    return data;
  }
}

class LanguageListResponse {
/*
{
  "success": true,
  "data": {
    "language": [
      {
        "id": 1,
        "name": "English",
        "code": "En",
        "url": "public/admin/product/image/collage-stu.png",
        "status": true,
        "created_at": null,
        "updated_at": null,
        "deleted_at": null
      }
    ]
  },
  "message": "support list."
}
*/

  bool? success;
  LanguageListResponseData? data;
  String? message;

  LanguageListResponse({
    this.success,
    this.data,
    this.message,
  });
  LanguageListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? LanguageListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
