///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MaintenanceResponse {
/*
{
  "success": false,
  "message": "App is UnderMaintanace"
}
*/

  bool? success;
  String? message;

  MaintenanceResponse({
    this.success,
    this.message,
  });
  MaintenanceResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["message"] = message;
    return data;
  }
}
