///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TagLineResponseDataTagLinePopularSearchProductProductName {
/*
{
  "id": 1,
  "product_id": 1,
  "name": "बीटरूट [बीट] - कापलेले",
  "descripation": "<div>उत्पादनाबद्दल</div><div>या खाद्य रूबी लाल मुळे गुळगुळीत आणि बल्ब आहेत. बीटरूटमध्ये इतर कोणत्याही भाज्यांपेक्षा साखरेचे प्रमाण सर्वाधिक असते.</div><div>आम्ही त्यांना ताजे आणि चिरलेले वितरित करतो, ज्यामुळे तुमची तयारी कमी गोंधळलेली आणि खूप सोपी होते.</div><div><br></div><div>साठवण आणि वापर</div><div>हे चिरलेले बीटरूट रेफ्रिजरेटरमध्ये 5 दिवसांपर्यंत ठेवता येतात.</div><div>ते करी, चटणी आणि रायठ्या तयार करण्यासाठी वापरले जातात. त्याचा गोड स्वभाव हा हॉलवे आणि अशा इतर मिठाईंसाठी एक लोकप्रिय घटक बनवतो.</div><div><br></div><div>लाभ</div><div>लाल बीट कमी रक्तदाब मेंदू आणि हृदयाच्या आरोग्यास प्रोत्साहन देते. हे जळजळांशी लढते आणि उर्जा पातळी वाढवते.</div>",
  "status": 1,
  "created_at": "2021-10-06T12:19:09.000000Z",
  "updated_at": "2021-10-06T12:40:32.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? productId;
  String? name;
  String? descripation;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  TagLineResponseDataTagLinePopularSearchProductProductName({
    this.id,
    this.productId,
    this.name,
    this.descripation,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  TagLineResponseDataTagLinePopularSearchProductProductName.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    productId = json["product_id"]?.toInt();
    name = json["name"]?.toString();
    descripation = json["descripation"]?.toString();
    status = json["status"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["product_id"] = productId;
    data["name"] = name;
    data["descripation"] = descripation;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class TagLineResponseDataTagLinePopularSearchProduct {
/*
{
  "id": 1,
  "name": "Beetroot [Beet] - sliced",
  "product_name": {
    "id": 1,
    "product_id": 1,
    "name": "बीटरूट [बीट] - कापलेले",
    "descripation": "<div>उत्पादनाबद्दल</div><div>या खाद्य रूबी लाल मुळे गुळगुळीत आणि बल्ब आहेत. बीटरूटमध्ये इतर कोणत्याही भाज्यांपेक्षा साखरेचे प्रमाण सर्वाधिक असते.</div><div>आम्ही त्यांना ताजे आणि चिरलेले वितरित करतो, ज्यामुळे तुमची तयारी कमी गोंधळलेली आणि खूप सोपी होते.</div><div><br></div><div>साठवण आणि वापर</div><div>हे चिरलेले बीटरूट रेफ्रिजरेटरमध्ये 5 दिवसांपर्यंत ठेवता येतात.</div><div>ते करी, चटणी आणि रायठ्या तयार करण्यासाठी वापरले जातात. त्याचा गोड स्वभाव हा हॉलवे आणि अशा इतर मिठाईंसाठी एक लोकप्रिय घटक बनवतो.</div><div><br></div><div>लाभ</div><div>लाल बीट कमी रक्तदाब मेंदू आणि हृदयाच्या आरोग्यास प्रोत्साहन देते. हे जळजळांशी लढते आणि उर्जा पातळी वाढवते.</div>",
    "status": 1,
    "created_at": "2021-10-06T12:19:09.000000Z",
    "updated_at": "2021-10-06T12:40:32.000000Z",
    "deleted_at": null
  }
}
*/

  int? id;
  String? name;
  TagLineResponseDataTagLinePopularSearchProductProductName? productName;

  TagLineResponseDataTagLinePopularSearchProduct({
    this.id,
    this.name,
    this.productName,
  });
  TagLineResponseDataTagLinePopularSearchProduct.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    productName = (json["product_name"] != null) ? TagLineResponseDataTagLinePopularSearchProductProductName.fromJson(json["product_name"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    if (productName != null) {
      data["product_name"] = productName!.toJson();
    }
    return data;
  }
}

class TagLineResponseDataTagLinePopularSearch {
/*
{
  "id": 1,
  "product_id": 1,
  "product": {
    "id": 1,
    "name": "Beetroot [Beet] - sliced",
    "product_name": {
      "id": 1,
      "product_id": 1,
      "name": "बीटरूट [बीट] - कापलेले",
      "descripation": "<div>उत्पादनाबद्दल</div><div>या खाद्य रूबी लाल मुळे गुळगुळीत आणि बल्ब आहेत. बीटरूटमध्ये इतर कोणत्याही भाज्यांपेक्षा साखरेचे प्रमाण सर्वाधिक असते.</div><div>आम्ही त्यांना ताजे आणि चिरलेले वितरित करतो, ज्यामुळे तुमची तयारी कमी गोंधळलेली आणि खूप सोपी होते.</div><div><br></div><div>साठवण आणि वापर</div><div>हे चिरलेले बीटरूट रेफ्रिजरेटरमध्ये 5 दिवसांपर्यंत ठेवता येतात.</div><div>ते करी, चटणी आणि रायठ्या तयार करण्यासाठी वापरले जातात. त्याचा गोड स्वभाव हा हॉलवे आणि अशा इतर मिठाईंसाठी एक लोकप्रिय घटक बनवतो.</div><div><br></div><div>लाभ</div><div>लाल बीट कमी रक्तदाब मेंदू आणि हृदयाच्या आरोग्यास प्रोत्साहन देते. हे जळजळांशी लढते आणि उर्जा पातळी वाढवते.</div>",
      "status": 1,
      "created_at": "2021-10-06T12:19:09.000000Z",
      "updated_at": "2021-10-06T12:40:32.000000Z",
      "deleted_at": null
    }
  }
}
*/

  int? id;
  int? productId;
  TagLineResponseDataTagLinePopularSearchProduct? product;

  TagLineResponseDataTagLinePopularSearch({
    this.id,
    this.productId,
    this.product,
  });
  TagLineResponseDataTagLinePopularSearch.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    productId = json["product_id"]?.toInt();
    product = (json["product"] != null) ? TagLineResponseDataTagLinePopularSearchProduct.fromJson(json["product"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["product_id"] = productId;
    if (product != null) {
      data["product"] = product!.toJson();
    }
    return data;
  }
}

class TagLineResponseDataTagLine {
/*
{
  "tag_line": "Ab market dur nahi!",
  "popular_search": [
    {
      "id": 1,
      "product_id": 1,
      "product": {
        "id": 1,
        "name": "Beetroot [Beet] - sliced",
        "product_name": {
          "id": 1,
          "product_id": 1,
          "name": "बीटरूट [बीट] - कापलेले",
          "descripation": "<div>उत्पादनाबद्दल</div><div>या खाद्य रूबी लाल मुळे गुळगुळीत आणि बल्ब आहेत. बीटरूटमध्ये इतर कोणत्याही भाज्यांपेक्षा साखरेचे प्रमाण सर्वाधिक असते.</div><div>आम्ही त्यांना ताजे आणि चिरलेले वितरित करतो, ज्यामुळे तुमची तयारी कमी गोंधळलेली आणि खूप सोपी होते.</div><div><br></div><div>साठवण आणि वापर</div><div>हे चिरलेले बीटरूट रेफ्रिजरेटरमध्ये 5 दिवसांपर्यंत ठेवता येतात.</div><div>ते करी, चटणी आणि रायठ्या तयार करण्यासाठी वापरले जातात. त्याचा गोड स्वभाव हा हॉलवे आणि अशा इतर मिठाईंसाठी एक लोकप्रिय घटक बनवतो.</div><div><br></div><div>लाभ</div><div>लाल बीट कमी रक्तदाब मेंदू आणि हृदयाच्या आरोग्यास प्रोत्साहन देते. हे जळजळांशी लढते आणि उर्जा पातळी वाढवते.</div>",
          "status": 1,
          "created_at": "2021-10-06T12:19:09.000000Z",
          "updated_at": "2021-10-06T12:40:32.000000Z",
          "deleted_at": null
        }
      }
    }
  ]
}
*/

  String? tagLine;
  List<TagLineResponseDataTagLinePopularSearch?>? popularSearch;

  TagLineResponseDataTagLine({
    this.tagLine,
    this.popularSearch,
  });
  TagLineResponseDataTagLine.fromJson(Map<String, dynamic> json) {
    tagLine = json["tag_line"]?.toString();
    if (json["popular_search"] != null) {
      final v = json["popular_search"];
      final arr0 = <TagLineResponseDataTagLinePopularSearch>[];
      v.forEach((v) {
        arr0.add(TagLineResponseDataTagLinePopularSearch.fromJson(v));
      });
      popularSearch = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["tag_line"] = tagLine;
    if (popularSearch != null) {
      final v = popularSearch;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["popular_search"] = arr0;
    }
    return data;
  }
}

class TagLineResponseData {
/*
{
  "tag_line": {
    "tag_line": "Ab market dur nahi!",
    "popular_search": [
      {
        "id": 1,
        "product_id": 1,
        "product": {
          "id": 1,
          "name": "Beetroot [Beet] - sliced",
          "product_name": {
            "id": 1,
            "product_id": 1,
            "name": "बीटरूट [बीट] - कापलेले",
            "descripation": "<div>उत्पादनाबद्दल</div><div>या खाद्य रूबी लाल मुळे गुळगुळीत आणि बल्ब आहेत. बीटरूटमध्ये इतर कोणत्याही भाज्यांपेक्षा साखरेचे प्रमाण सर्वाधिक असते.</div><div>आम्ही त्यांना ताजे आणि चिरलेले वितरित करतो, ज्यामुळे तुमची तयारी कमी गोंधळलेली आणि खूप सोपी होते.</div><div><br></div><div>साठवण आणि वापर</div><div>हे चिरलेले बीटरूट रेफ्रिजरेटरमध्ये 5 दिवसांपर्यंत ठेवता येतात.</div><div>ते करी, चटणी आणि रायठ्या तयार करण्यासाठी वापरले जातात. त्याचा गोड स्वभाव हा हॉलवे आणि अशा इतर मिठाईंसाठी एक लोकप्रिय घटक बनवतो.</div><div><br></div><div>लाभ</div><div>लाल बीट कमी रक्तदाब मेंदू आणि हृदयाच्या आरोग्यास प्रोत्साहन देते. हे जळजळांशी लढते आणि उर्जा पातळी वाढवते.</div>",
            "status": 1,
            "created_at": "2021-10-06T12:19:09.000000Z",
            "updated_at": "2021-10-06T12:40:32.000000Z",
            "deleted_at": null
          }
        }
      }
    ]
  }
}
*/

  TagLineResponseDataTagLine? tagLine;

  TagLineResponseData({
    this.tagLine,
  });
  TagLineResponseData.fromJson(Map<String, dynamic> json) {
    tagLine = (json["tag_line"] != null) ? TagLineResponseDataTagLine.fromJson(json["tag_line"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (tagLine != null) {
      data["tag_line"] = tagLine!.toJson();
    }
    return data;
  }
}

class TagLineResponse {
/*
{
  "success": true,
  "data": {
    "tag_line": {
      "tag_line": "Ab market dur nahi!",
      "popular_search": [
        {
          "id": 1,
          "product_id": 1,
          "product": {
            "id": 1,
            "name": "Beetroot [Beet] - sliced",
            "product_name": {
              "id": 1,
              "product_id": 1,
              "name": "बीटरूट [बीट] - कापलेले",
              "descripation": "<div>उत्पादनाबद्दल</div><div>या खाद्य रूबी लाल मुळे गुळगुळीत आणि बल्ब आहेत. बीटरूटमध्ये इतर कोणत्याही भाज्यांपेक्षा साखरेचे प्रमाण सर्वाधिक असते.</div><div>आम्ही त्यांना ताजे आणि चिरलेले वितरित करतो, ज्यामुळे तुमची तयारी कमी गोंधळलेली आणि खूप सोपी होते.</div><div><br></div><div>साठवण आणि वापर</div><div>हे चिरलेले बीटरूट रेफ्रिजरेटरमध्ये 5 दिवसांपर्यंत ठेवता येतात.</div><div>ते करी, चटणी आणि रायठ्या तयार करण्यासाठी वापरले जातात. त्याचा गोड स्वभाव हा हॉलवे आणि अशा इतर मिठाईंसाठी एक लोकप्रिय घटक बनवतो.</div><div><br></div><div>लाभ</div><div>लाल बीट कमी रक्तदाब मेंदू आणि हृदयाच्या आरोग्यास प्रोत्साहन देते. हे जळजळांशी लढते आणि उर्जा पातळी वाढवते.</div>",
              "status": 1,
              "created_at": "2021-10-06T12:19:09.000000Z",
              "updated_at": "2021-10-06T12:40:32.000000Z",
              "deleted_at": null
            }
          }
        }
      ]
    }
  },
  "message": "Product Search."
}
*/

  bool? success;
  TagLineResponseData? data;
  String? message;

  TagLineResponse({
    this.success,
    this.data,
    this.message,
  });
  TagLineResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? TagLineResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
