///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EaseBuzzPaymentInitResponse {
/*
{
  "status": 1,
  "data": "60af0189c72d71c0cb78a30cadc9c810eb76cefe48c5a5b46cbf1a256a439593"
}
*/

  int? status;
  String? data;

  EaseBuzzPaymentInitResponse({
    this.status,
    this.data,
  });
  EaseBuzzPaymentInitResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['data'] = this.data;
    return data;
  }
}
