///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EaseBuzzPaymentResponse {
/*
{
  "txnid": "1001",
  "firstname": "John Doe",
  "email": "johndoe@gmail.com",
  "phone": "9876543210",
  "key": "DF3252FDSF",
  "mode": "DC",
  "status": "success",
  "unmappedstatus": "failed",
  "cardCategory": "domestic",
  "addedon": "2016-07-22 17:17:08",
  "payment_source": "Easebuzz",
  "PG_TYPE": "SBIPG",
  "bank_ref_num": "",
  "bankcode": "MAST",
  "error": "E600",
  "error_msg": "Bank denied transaction on card.",
  "name_on_card": "John",
  "cardnum": "519620XXXXXX7840",
  "issuing_bank": "",
  "card_type": "",
  "easepayid": "H5T2RYZKW",
  "amount": "100.00",
  "net_amount_debit": "100.00",
  "cash_back_percentage": "50",
  "deduction_percentage": "2.50",
  "productinfo": "Tshirt",
  "udf10": "",
  "udf9": "",
  "udf8": "",
  "udf7": "",
  "udf6": "",
  "udf5": "",
  "udf4": "",
  "udf3": "",
  "udf2": "",
  "udf1": "",
  "hash": "ce2d0588f8648c62db86475d343d3433d00b87827502c676a093730f04cec5fea2eb0e8bb"
}
*/

  String? txnid;
  String? firstname;
  String? email;
  String? phone;
  String? key;
  String? mode;
  String? status;
  String? unmappedstatus;
  String? cardCategory;
  String? addedon;
  String? paymentSource;
  String? PGTYPE;
  String? bankRefNum;
  String? bankcode;
  String? error;
  String? errorMsg;
  String? nameOnCard;
  String? cardnum;
  String? issuingBank;
  String? cardType;
  String? easepayid;
  String? amount;
  String? netAmountDebit;
  String? cashBackPercentage;
  String? deductionPercentage;
  String? productinfo;
  String? udf10;
  String? udf9;
  String? udf8;
  String? udf7;
  String? udf6;
  String? udf5;
  String? udf4;
  String? udf3;
  String? udf2;
  String? udf1;
  String? hash;

  EaseBuzzPaymentResponse({
    this.txnid,
    this.firstname,
    this.email,
    this.phone,
    this.key,
    this.mode,
    this.status,
    this.unmappedstatus,
    this.cardCategory,
    this.addedon,
    this.paymentSource,
    this.PGTYPE,
    this.bankRefNum,
    this.bankcode,
    this.error,
    this.errorMsg,
    this.nameOnCard,
    this.cardnum,
    this.issuingBank,
    this.cardType,
    this.easepayid,
    this.amount,
    this.netAmountDebit,
    this.cashBackPercentage,
    this.deductionPercentage,
    this.productinfo,
    this.udf10,
    this.udf9,
    this.udf8,
    this.udf7,
    this.udf6,
    this.udf5,
    this.udf4,
    this.udf3,
    this.udf2,
    this.udf1,
    this.hash,
  });
  EaseBuzzPaymentResponse.fromJson(Map<String, dynamic> json) {
    txnid = json['txnid']?.toString();
    firstname = json['firstname']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    key = json['key']?.toString();
    mode = json['mode']?.toString();
    status = json['status']?.toString();
    unmappedstatus = json['unmappedstatus']?.toString();
    cardCategory = json['cardCategory']?.toString();
    addedon = json['addedon']?.toString();
    paymentSource = json['payment_source']?.toString();
    PGTYPE = json['PG_TYPE']?.toString();
    bankRefNum = json['bank_ref_num']?.toString();
    bankcode = json['bankcode']?.toString();
    error = json['error']?.toString();
    errorMsg = json['error_msg']?.toString();
    nameOnCard = json['name_on_card']?.toString();
    cardnum = json['cardnum']?.toString();
    issuingBank = json['issuing_bank']?.toString();
    cardType = json['card_type']?.toString();
    easepayid = json['easepayid']?.toString();
    amount = json['amount']?.toString();
    netAmountDebit = json['net_amount_debit']?.toString();
    cashBackPercentage = json['cash_back_percentage']?.toString();
    deductionPercentage = json['deduction_percentage']?.toString();
    productinfo = json['productinfo']?.toString();
    udf10 = json['udf10']?.toString();
    udf9 = json['udf9']?.toString();
    udf8 = json['udf8']?.toString();
    udf7 = json['udf7']?.toString();
    udf6 = json['udf6']?.toString();
    udf5 = json['udf5']?.toString();
    udf4 = json['udf4']?.toString();
    udf3 = json['udf3']?.toString();
    udf2 = json['udf2']?.toString();
    udf1 = json['udf1']?.toString();
    hash = json['hash']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['txnid'] = txnid;
    data['firstname'] = firstname;
    data['email'] = email;
    data['phone'] = phone;
    data['key'] = key;
    data['mode'] = mode;
    data['status'] = status;
    data['unmappedstatus'] = unmappedstatus;
    data['cardCategory'] = cardCategory;
    data['addedon'] = addedon;
    data['payment_source'] = paymentSource;
    data['PG_TYPE'] = PGTYPE;
    data['bank_ref_num'] = bankRefNum;
    data['bankcode'] = bankcode;
    data['error'] = error;
    data['error_msg'] = errorMsg;
    data['name_on_card'] = nameOnCard;
    data['cardnum'] = cardnum;
    data['issuing_bank'] = issuingBank;
    data['card_type'] = cardType;
    data['easepayid'] = easepayid;
    data['amount'] = amount;
    data['net_amount_debit'] = netAmountDebit;
    data['cash_back_percentage'] = cashBackPercentage;
    data['deduction_percentage'] = deductionPercentage;
    data['productinfo'] = productinfo;
    data['udf10'] = udf10;
    data['udf9'] = udf9;
    data['udf8'] = udf8;
    data['udf7'] = udf7;
    data['udf6'] = udf6;
    data['udf5'] = udf5;
    data['udf4'] = udf4;
    data['udf3'] = udf3;
    data['udf2'] = udf2;
    data['udf1'] = udf1;
    data['hash'] = hash;
    return data;
  }
}
