///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BannerResponseDataBanner {
/*
{
  "id": 1,
  "user_id": 1,
  "type": "Home",
  "name": "Order Your Fresh",
  "image": "public/admin/home/banner/Group 335.png",
  "status": true,
  "created_at": "2021-08-24T08:54:55.000000Z",
  "updated_at": "2021-08-24T13:11:58.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? type;
  String? name;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  BannerResponseDataBanner({
    this.id,
    this.userId,
    this.type,
    this.name,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  BannerResponseDataBanner.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    type = json["type"]?.toString();
    name = json["name"]?.toString();
    image = json["image"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["type"] = type;
    data["name"] = name;
    data["image"] = image;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class BannerResponseData {
/*
{
  "banner": [
    {
      "id": 1,
      "user_id": 1,
      "type": "Home",
      "name": "Order Your Fresh",
      "image": "public/admin/home/banner/Group 335.png",
      "status": true,
      "created_at": "2021-08-24T08:54:55.000000Z",
      "updated_at": "2021-08-24T13:11:58.000000Z",
      "deleted_at": null
    }
  ]
}
*/

  List<BannerResponseDataBanner?>? banner;

  BannerResponseData({
    this.banner,
  });
  BannerResponseData.fromJson(Map<String, dynamic> json) {
    if (json["banner"] != null) {
      final v = json["banner"];
      final arr0 = <BannerResponseDataBanner>[];
      v.forEach((v) {
        arr0.add(BannerResponseDataBanner.fromJson(v));
      });
      banner = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (banner != null) {
      final v = banner;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["banner"] = arr0;
    }
    return data;
  }
}

class BannerResponse {
/*
{
  "success": true,
  "data": {
    "banner": [
      {
        "id": 1,
        "user_id": 1,
        "type": "Home",
        "name": "Order Your Fresh",
        "image": "public/admin/home/banner/Group 335.png",
        "status": true,
        "created_at": "2021-08-24T08:54:55.000000Z",
        "updated_at": "2021-08-24T13:11:58.000000Z",
        "deleted_at": null
      }
    ]
  },
  "message": "Banner list."
}
*/

  bool? success;
  BannerResponseData? data;
  String? message;

  BannerResponse({
    this.success,
    this.data,
    this.message,
  });
  BannerResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? BannerResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["data"] = this.data!.toJson();
    data["message"] = message;
    return data;
  }
}
