///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreditListResponseDataCreditCreditBy {
/*
{
  "id": 2,
  "name": "jayesh",
  "email": null,
  "mobile_number": "7304610113",
  "shope_name": null,
  "address": null,
  "pincode": null,
  "latitude": null,
  "longitude": null,
  "shope_type_id": null,
  "sales_executive": null,
  "email_verified_at": null,
  "type": "customer",
  "version": "1.0.0",
  "status": true,
  "created_at": "2021-08-27T06:12:47.000000Z",
  "updated_at": "2021-08-30T04:31:13.000000Z"
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? shopeName;
  String? address;
  String? pincode;
  String? latitude;
  String? longitude;
  String? shopeTypeId;
  String? salesExecutive;
  String? emailVerifiedAt;
  String? type;
  String? version;
  bool? status;
  String? createdAt;
  String? updatedAt;

  CreditListResponseDataCreditCreditBy({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.shopeName,
    this.address,
    this.pincode,
    this.latitude,
    this.longitude,
    this.shopeTypeId,
    this.salesExecutive,
    this.emailVerifiedAt,
    this.type,
    this.version,
    this.status,
    this.createdAt,
    this.updatedAt,
  });
  CreditListResponseDataCreditCreditBy.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    shopeName = json["shope_name"]?.toString();
    address = json["address"]?.toString();
    pincode = json["pincode"]?.toString();
    latitude = json["latitude"]?.toString();
    longitude = json["longitude"]?.toString();
    shopeTypeId = json["shope_type_id"]?.toString();
    salesExecutive = json["sales_executive"]?.toString();
    emailVerifiedAt = json["email_verified_at"]?.toString();
    type = json["type"]?.toString();
    version = json["version"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["shope_name"] = shopeName;
    data["address"] = address;
    data["pincode"] = pincode;
    data["latitude"] = latitude;
    data["longitude"] = longitude;
    data["shope_type_id"] = shopeTypeId;
    data["sales_executive"] = salesExecutive;
    data["email_verified_at"] = emailVerifiedAt;
    data["type"] = type;
    data["version"] = version;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    return data;
  }
}

class CreditListResponseDataCredit {
/*
{
  "id": 2,
  "customer_id": 2,
  "payment_id": 1,
  "created_by": 2,
  "amount": "100.00",
  "comment": "razorpay",
  "type": "credit",
  "status": true,
  "created_at": "2021-08-30T06:50:23.000000Z",
  "updated_at": "2021-08-30T06:50:23.000000Z",
  "deleted_at": null,
  "credit_by": {
    "id": 2,
    "name": "jayesh",
    "email": null,
    "mobile_number": "7304610113",
    "shope_name": null,
    "address": null,
    "pincode": null,
    "latitude": null,
    "longitude": null,
    "shope_type_id": null,
    "sales_executive": null,
    "email_verified_at": null,
    "type": "customer",
    "version": "1.0.0",
    "status": true,
    "created_at": "2021-08-27T06:12:47.000000Z",
    "updated_at": "2021-08-30T04:31:13.000000Z"
  }
}
*/

  int? id;
  int? customerId;
  int? paymentId;
  int? createdBy;
  String? amount;
  String? comment;
  String? type;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  CreditListResponseDataCreditCreditBy? creditBy;

  CreditListResponseDataCredit({
    this.id,
    this.customerId,
    this.paymentId,
    this.createdBy,
    this.amount,
    this.comment,
    this.type,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.creditBy,
  });
  CreditListResponseDataCredit.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    customerId = json["customer_id"]?.toInt();
    paymentId = json["payment_id"]?.toInt();
    createdBy = json["created_by"]?.toInt();
    amount = json["amount"]?.toString();
    comment = json["comment"]?.toString();
    type = json["type"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    creditBy = (json["credit_by"] != null) ? CreditListResponseDataCreditCreditBy.fromJson(json["credit_by"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["customer_id"] = customerId;
    data["payment_id"] = paymentId;
    data["created_by"] = createdBy;
    data["amount"] = amount;
    data["comment"] = comment;
    data["type"] = type;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    if (creditBy != null) {
      data["credit_by"] = creditBy!.toJson();
    }
    return data;
  }
}

class CreditListResponseData {
/*
{
  "credit": [
    {
      "id": 2,
      "customer_id": 2,
      "payment_id": 1,
      "created_by": 2,
      "amount": "100.00",
      "comment": "razorpay",
      "type": "credit",
      "status": true,
      "created_at": "2021-08-30T06:50:23.000000Z",
      "updated_at": "2021-08-30T06:50:23.000000Z",
      "deleted_at": null,
      "credit_by": {
        "id": 2,
        "name": "jayesh",
        "email": null,
        "mobile_number": "7304610113",
        "shope_name": null,
        "address": null,
        "pincode": null,
        "latitude": null,
        "longitude": null,
        "shope_type_id": null,
        "sales_executive": null,
        "email_verified_at": null,
        "type": "customer",
        "version": "1.0.0",
        "status": true,
        "created_at": "2021-08-27T06:12:47.000000Z",
        "updated_at": "2021-08-30T04:31:13.000000Z"
      }
    }
  ]
}
*/

  List<CreditListResponseDataCredit?>? credit;

  CreditListResponseData({
    this.credit,
  });
  CreditListResponseData.fromJson(Map<String, dynamic> json) {
    if (json["credit"] != null) {
      final v = json["credit"];
      final arr0 = <CreditListResponseDataCredit>[];
      v.forEach((v) {
        arr0.add(CreditListResponseDataCredit.fromJson(v));
      });
      credit = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (credit != null) {
      final v = credit;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["credit"] = arr0;
    }
    return data;
  }
}

class CreditListResponse {
/*
{
  "success": true,
  "data": {
    "credit": [
      {
        "id": 2,
        "customer_id": 2,
        "payment_id": 1,
        "created_by": 2,
        "amount": "100.00",
        "comment": "razorpay",
        "type": "credit",
        "status": true,
        "created_at": "2021-08-30T06:50:23.000000Z",
        "updated_at": "2021-08-30T06:50:23.000000Z",
        "deleted_at": null,
        "credit_by": {
          "id": 2,
          "name": "jayesh",
          "email": null,
          "mobile_number": "7304610113",
          "shope_name": null,
          "address": null,
          "pincode": null,
          "latitude": null,
          "longitude": null,
          "shope_type_id": null,
          "sales_executive": null,
          "email_verified_at": null,
          "type": "customer",
          "version": "1.0.0",
          "status": true,
          "created_at": "2021-08-27T06:12:47.000000Z",
          "updated_at": "2021-08-30T04:31:13.000000Z"
        }
      }
    ]
  },
  "message": "Wallet list."
}
*/

  bool? success;
  CreditListResponseData? data;
  String? message;

  CreditListResponse({
    this.success,
    this.data,
    this.message,
  });
  CreditListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? CreditListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
