///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WalletResponseData {
/*
{
  "wallet": "900.00"
}
*/

  String? wallet;

  WalletResponseData({
    this.wallet,
  });
  WalletResponseData.fromJson(Map<String, dynamic> json) {
    wallet = json["wallet"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["wallet"] = wallet;
    return data;
  }
}

class WalletResponse {
/*
{
  "success": true,
  "data": {
    "wallet": "900.00"
  },
  "message": "Wallet list."
}
*/

  bool? success;
  WalletResponseData? data;
  String? message;

  WalletResponse({
    this.success,
    this.data,
    this.message,
  });
  WalletResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? WalletResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
