///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderCancelResponseData {
/*
{
  "order_id": "90",
  "sucees": "SucessFully Cancel"
}
*/

  String? orderId;
  String? sucees;

  OrderCancelResponseData({
    this.orderId,
    this.sucees,
  });
  OrderCancelResponseData.fromJson(Map<String, dynamic> json) {
    orderId = json["order_id"]?.toString();
    sucees = json["sucees"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["order_id"] = orderId;
    data["sucees"] = sucees;
    return data;
  }
}

class OrderCancelResponse {
/*
{
  "success": true,
  "data": {
    "order_id": "90",
    "sucees": "SucessFully Cancel"
  },
  "message": " successfully."
}
*/

  bool? success;
  OrderCancelResponseData? data;
  String? message;

  OrderCancelResponse({
    this.success,
    this.data,
    this.message,
  });
  OrderCancelResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? OrderCancelResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
