///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderPlaceResponseData {
/*
{
  "order_id": 9,
  "order_no": 3008218
}
*/

  int? orderId;
  int? orderNo;

  OrderPlaceResponseData({
    this.orderId,
    this.orderNo,
  });
  OrderPlaceResponseData.fromJson(Map<String, dynamic> json) {
    orderId = json["order_id"]?.toInt();
    orderNo = json["order_no"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["order_id"] = orderId;
    data["order_no"] = orderNo;
    return data;
  }
}

class OrderPlaceResponse {
/*
{
  "success": true,
  "data": {
    "order_id": 9,
    "order_no": 3008218
  },
  "message": " successfully."
}
*/

  bool? success;
  OrderPlaceResponseData? data;
  String? message;

  OrderPlaceResponse({
    this.success,
    this.data,
    this.message,
  });
  OrderPlaceResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? OrderPlaceResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
