///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderPaymentResponseData {
/*
{
  "order_id": "204"
}
*/

  String? orderId;

  OrderPaymentResponseData({
    this.orderId,
  });
  OrderPaymentResponseData.fromJson(Map<String, dynamic> json) {
    orderId = json["order_id"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["order_id"] = orderId;
    return data;
  }
}

class OrderPaymentResponse {
/*
{
  "success": true,
  "data": {
    "order_id": "204"
  },
  "message": " successfully."
}
*/

  bool? success;
  OrderPaymentResponseData? data;
  String? message;

  OrderPaymentResponse({
    this.success,
    this.data,
    this.message,
  });
  OrderPaymentResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? OrderPaymentResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
