///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderHistoryListResponseDataOrderLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  OrderHistoryListResponseDataOrderLinks({
    this.url,
    this.label,
    this.active,
  });
  OrderHistoryListResponseDataOrderLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class OrderHistoryListResponseDataOrderDataOrderStatus {
/*
{
  "id": 6,
  "user_id": 1,
  "name": "Cancel",
  "status": true,
  "created_at": "2021-09-06T04:59:22.000000Z",
  "updated_at": "2021-09-06T04:59:22.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? name;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  OrderHistoryListResponseDataOrderDataOrderStatus({
    this.id,
    this.userId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  OrderHistoryListResponseDataOrderDataOrderStatus.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    name = json["name"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["name"] = name;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class OrderHistoryListResponseDataOrderDataTimeSlot {
/*
{
  "id": 2,
  "s_time": "16:00:04",
  "e_time": "20:00:17",
  "status": true,
  "created_at": "2021-08-24T19:57:53.000000Z",
  "updated_at": null,
  "deleted_at": null
}
*/

  int? id;
  String? sTime;
  String? eTime;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  OrderHistoryListResponseDataOrderDataTimeSlot({
    this.id,
    this.sTime,
    this.eTime,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  OrderHistoryListResponseDataOrderDataTimeSlot.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    sTime = json["s_time"]?.toString();
    eTime = json["e_time"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["s_time"] = sTime;
    data["e_time"] = eTime;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class OrderHistoryListResponseDataOrderDataOrderPaymentStatusPaymentStatus {
/*
{
  "id": 2,
  "user_id": 1,
  "name": "Un Paid",
  "status": true,
  "created_at": "2021-08-31T20:06:46.000000Z",
  "updated_at": null,
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? name;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  OrderHistoryListResponseDataOrderDataOrderPaymentStatusPaymentStatus({
    this.id,
    this.userId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  OrderHistoryListResponseDataOrderDataOrderPaymentStatusPaymentStatus.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    name = json["name"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["name"] = name;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class OrderHistoryListResponseDataOrderDataOrderPaymentStatus {
/*
{
  "id": 93,
  "user_id": 3,
  "order_id": 94,
  "payment_statu_id": 2,
  "token_id": null,
  "type": "COD",
  "status": true,
  "created_at": "2021-10-07T07:38:35.000000Z",
  "updated_at": "2021-10-07T07:38:35.000000Z",
  "deleted_at": null,
  "razor_payment_id": null,
  "razor_order_id": null,
  "signature": null,
  "payment_status": {
    "id": 2,
    "user_id": 1,
    "name": "Un Paid",
    "status": true,
    "created_at": "2021-08-31T20:06:46.000000Z",
    "updated_at": null,
    "deleted_at": null
  }
}
*/

  int? id;
  int? userId;
  int? orderId;
  int? paymentStatuId;
  String? tokenId;
  String? type;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? razorPaymentId;
  String? razorOrderId;
  String? signature;
  OrderHistoryListResponseDataOrderDataOrderPaymentStatusPaymentStatus? paymentStatus;

  OrderHistoryListResponseDataOrderDataOrderPaymentStatus({
    this.id,
    this.userId,
    this.orderId,
    this.paymentStatuId,
    this.tokenId,
    this.type,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.razorPaymentId,
    this.razorOrderId,
    this.signature,
    this.paymentStatus,
  });
  OrderHistoryListResponseDataOrderDataOrderPaymentStatus.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    orderId = json["order_id"]?.toInt();
    paymentStatuId = json["payment_statu_id"]?.toInt();
    tokenId = json["token_id"]?.toString();
    type = json["type"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    razorPaymentId = json["razor_payment_id"]?.toString();
    razorOrderId = json["razor_order_id"]?.toString();
    signature = json["signature"]?.toString();
    paymentStatus = (json["payment_status"] != null) ? OrderHistoryListResponseDataOrderDataOrderPaymentStatusPaymentStatus.fromJson(json["payment_status"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["order_id"] = orderId;
    data["payment_statu_id"] = paymentStatuId;
    data["token_id"] = tokenId;
    data["type"] = type;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    data["razor_payment_id"] = razorPaymentId;
    data["razor_order_id"] = razorOrderId;
    data["signature"] = signature;
    if (paymentStatus != null) {
      data["payment_status"] = paymentStatus!.toJson();
    }
    return data;
  }
}

class OrderHistoryListResponseDataOrderData {
/*
{
  "id": 94,
  "user_id": 3,
  "order_id": "7102194",
  "customer_address_id": 61,
  "longitude": null,
  "latitude": null,
  "pincode": null,
  "address": null,
  "land_mark": null,
  "mobile": null,
  "name": null,
  "city_id": null,
  "state_id": null,
  "country_id": null,
  "time_slot_id": 2,
  "total_quantity": 11,
  "total_price": "152.50",
  "order_status_id": 6,
  "status": true,
  "created_at": "2021-10-07T07:38:34.000000Z",
  "updated_at": "2021-10-11T05:22:15.000000Z",
  "deleted_at": null,
  "delivery_date": "2021-10-07",
  "order_from": "mobile",
  "order_payment_status": {
    "id": 93,
    "user_id": 3,
    "order_id": 94,
    "payment_statu_id": 2,
    "token_id": null,
    "type": "COD",
    "status": true,
    "created_at": "2021-10-07T07:38:35.000000Z",
    "updated_at": "2021-10-07T07:38:35.000000Z",
    "deleted_at": null,
    "razor_payment_id": null,
    "razor_order_id": null,
    "signature": null,
    "payment_status": {
      "id": 2,
      "user_id": 1,
      "name": "Un Paid",
      "status": true,
      "created_at": "2021-08-31T20:06:46.000000Z",
      "updated_at": null,
      "deleted_at": null
    }
  },
  "time_slot": {
    "id": 2,
    "s_time": "16:00:04",
    "e_time": "20:00:17",
    "status": true,
    "created_at": "2021-08-24T19:57:53.000000Z",
    "updated_at": null,
    "deleted_at": null
  },
  "order_status": {
    "id": 6,
    "user_id": 1,
    "name": "Cancel",
    "status": true,
    "created_at": "2021-09-06T04:59:22.000000Z",
    "updated_at": "2021-09-06T04:59:22.000000Z",
    "deleted_at": null
  }
}
*/

  int? id;
  int? userId;
  String? orderId;
  int? customerAddressId;
  String? longitude;
  String? latitude;
  String? pincode;
  String? address;
  String? landMark;
  String? mobile;
  String? name;
  String? cityId;
  String? stateId;
  String? countryId;
  int? timeSlotId;
  int? totalQuantity;
  String? totalPrice;
  int? orderStatusId;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? deliveryDate;
  String? orderFrom;
  OrderHistoryListResponseDataOrderDataOrderPaymentStatus? orderPaymentStatus;
  OrderHistoryListResponseDataOrderDataTimeSlot? timeSlot;
  OrderHistoryListResponseDataOrderDataOrderStatus? orderStatus;

  OrderHistoryListResponseDataOrderData({
    this.id,
    this.userId,
    this.orderId,
    this.customerAddressId,
    this.longitude,
    this.latitude,
    this.pincode,
    this.address,
    this.landMark,
    this.mobile,
    this.name,
    this.cityId,
    this.stateId,
    this.countryId,
    this.timeSlotId,
    this.totalQuantity,
    this.totalPrice,
    this.orderStatusId,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.deliveryDate,
    this.orderFrom,
    this.orderPaymentStatus,
    this.timeSlot,
    this.orderStatus,
  });
  OrderHistoryListResponseDataOrderData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    orderId = json["order_id"]?.toString();
    customerAddressId = json["customer_address_id"]?.toInt();
    longitude = json["longitude"]?.toString();
    latitude = json["latitude"]?.toString();
    pincode = json["pincode"]?.toString();
    address = json["address"]?.toString();
    landMark = json["land_mark"]?.toString();
    mobile = json["mobile"]?.toString();
    name = json["name"]?.toString();
    cityId = json["city_id"]?.toString();
    stateId = json["state_id"]?.toString();
    countryId = json["country_id"]?.toString();
    timeSlotId = json["time_slot_id"]?.toInt();
    totalQuantity = json["total_quantity"]?.toInt();
    totalPrice = json["total_price"]?.toString();
    orderStatusId = json["order_status_id"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    deliveryDate = json["delivery_date"]?.toString();
    orderFrom = json["order_from"]?.toString();
    orderPaymentStatus = (json["order_payment_status"] != null) ? OrderHistoryListResponseDataOrderDataOrderPaymentStatus.fromJson(json["order_payment_status"]) : null;
    timeSlot = (json["time_slot"] != null) ? OrderHistoryListResponseDataOrderDataTimeSlot.fromJson(json["time_slot"]) : null;
    orderStatus = (json["order_status"] != null) ? OrderHistoryListResponseDataOrderDataOrderStatus.fromJson(json["order_status"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["order_id"] = orderId;
    data["customer_address_id"] = customerAddressId;
    data["longitude"] = longitude;
    data["latitude"] = latitude;
    data["pincode"] = pincode;
    data["address"] = address;
    data["land_mark"] = landMark;
    data["mobile"] = mobile;
    data["name"] = name;
    data["city_id"] = cityId;
    data["state_id"] = stateId;
    data["country_id"] = countryId;
    data["time_slot_id"] = timeSlotId;
    data["total_quantity"] = totalQuantity;
    data["total_price"] = totalPrice;
    data["order_status_id"] = orderStatusId;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    data["delivery_date"] = deliveryDate;
    data["order_from"] = orderFrom;
    if (orderPaymentStatus != null) {
      data["order_payment_status"] = orderPaymentStatus!.toJson();
    }
    if (timeSlot != null) {
      data["time_slot"] = timeSlot!.toJson();
    }
    if (orderStatus != null) {
      data["order_status"] = orderStatus!.toJson();
    }
    return data;
  }
}

class OrderHistoryListResponseDataOrder {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 94,
      "user_id": 3,
      "order_id": "7102194",
      "customer_address_id": 61,
      "longitude": null,
      "latitude": null,
      "pincode": null,
      "address": null,
      "land_mark": null,
      "mobile": null,
      "name": null,
      "city_id": null,
      "state_id": null,
      "country_id": null,
      "time_slot_id": 2,
      "total_quantity": 11,
      "total_price": "152.50",
      "order_status_id": 6,
      "status": true,
      "created_at": "2021-10-07T07:38:34.000000Z",
      "updated_at": "2021-10-11T05:22:15.000000Z",
      "deleted_at": null,
      "delivery_date": "2021-10-07",
      "order_from": "mobile",
      "order_payment_status": {
        "id": 93,
        "user_id": 3,
        "order_id": 94,
        "payment_statu_id": 2,
        "token_id": null,
        "type": "COD",
        "status": true,
        "created_at": "2021-10-07T07:38:35.000000Z",
        "updated_at": "2021-10-07T07:38:35.000000Z",
        "deleted_at": null,
        "razor_payment_id": null,
        "razor_order_id": null,
        "signature": null,
        "payment_status": {
          "id": 2,
          "user_id": 1,
          "name": "Un Paid",
          "status": true,
          "created_at": "2021-08-31T20:06:46.000000Z",
          "updated_at": null,
          "deleted_at": null
        }
      },
      "time_slot": {
        "id": 2,
        "s_time": "16:00:04",
        "e_time": "20:00:17",
        "status": true,
        "created_at": "2021-08-24T19:57:53.000000Z",
        "updated_at": null,
        "deleted_at": null
      },
      "order_status": {
        "id": 6,
        "user_id": 1,
        "name": "Cancel",
        "status": true,
        "created_at": "2021-09-06T04:59:22.000000Z",
        "updated_at": "2021-09-06T04:59:22.000000Z",
        "deleted_at": null
      }
    }
  ],
  "first_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=1",
  "from": 1,
  "last_page": 2,
  "last_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=2",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=2",
  "path": "http://192.168.10.8/vidarbha/public/api/order",
  "per_page": 10,
  "prev_page_url": null,
  "to": 10,
  "total": 18
}
*/

  int? currentPage;
  List<OrderHistoryListResponseDataOrderData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<OrderHistoryListResponseDataOrderLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  OrderHistoryListResponseDataOrder({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  OrderHistoryListResponseDataOrder.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <OrderHistoryListResponseDataOrderData>[];
      v.forEach((v) {
        arr0.add(OrderHistoryListResponseDataOrderData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <OrderHistoryListResponseDataOrderLinks>[];
      v.forEach((v) {
        arr0.add(OrderHistoryListResponseDataOrderLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class OrderHistoryListResponseData {
/*
{
  "order": {
    "current_page": 1,
    "data": [
      {
        "id": 94,
        "user_id": 3,
        "order_id": "7102194",
        "customer_address_id": 61,
        "longitude": null,
        "latitude": null,
        "pincode": null,
        "address": null,
        "land_mark": null,
        "mobile": null,
        "name": null,
        "city_id": null,
        "state_id": null,
        "country_id": null,
        "time_slot_id": 2,
        "total_quantity": 11,
        "total_price": "152.50",
        "order_status_id": 6,
        "status": true,
        "created_at": "2021-10-07T07:38:34.000000Z",
        "updated_at": "2021-10-11T05:22:15.000000Z",
        "deleted_at": null,
        "delivery_date": "2021-10-07",
        "order_from": "mobile",
        "order_payment_status": {
          "id": 93,
          "user_id": 3,
          "order_id": 94,
          "payment_statu_id": 2,
          "token_id": null,
          "type": "COD",
          "status": true,
          "created_at": "2021-10-07T07:38:35.000000Z",
          "updated_at": "2021-10-07T07:38:35.000000Z",
          "deleted_at": null,
          "razor_payment_id": null,
          "razor_order_id": null,
          "signature": null,
          "payment_status": {
            "id": 2,
            "user_id": 1,
            "name": "Un Paid",
            "status": true,
            "created_at": "2021-08-31T20:06:46.000000Z",
            "updated_at": null,
            "deleted_at": null
          }
        },
        "time_slot": {
          "id": 2,
          "s_time": "16:00:04",
          "e_time": "20:00:17",
          "status": true,
          "created_at": "2021-08-24T19:57:53.000000Z",
          "updated_at": null,
          "deleted_at": null
        },
        "order_status": {
          "id": 6,
          "user_id": 1,
          "name": "Cancel",
          "status": true,
          "created_at": "2021-09-06T04:59:22.000000Z",
          "updated_at": "2021-09-06T04:59:22.000000Z",
          "deleted_at": null
        }
      }
    ],
    "first_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=1",
    "from": 1,
    "last_page": 2,
    "last_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=2",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=2",
    "path": "http://192.168.10.8/vidarbha/public/api/order",
    "per_page": 10,
    "prev_page_url": null,
    "to": 10,
    "total": 18
  }
}
*/

  OrderHistoryListResponseDataOrder? order;

  OrderHistoryListResponseData({
    this.order,
  });
  OrderHistoryListResponseData.fromJson(Map<String, dynamic> json) {
    order = (json["order"] != null) ? OrderHistoryListResponseDataOrder.fromJson(json["order"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (order != null) {
      data["order"] = order!.toJson();
    }
    return data;
  }
}

class OrderHistoryListResponse {
/*
{
  "success": true,
  "data": {
    "order": {
      "current_page": 1,
      "data": [
        {
          "id": 94,
          "user_id": 3,
          "order_id": "7102194",
          "customer_address_id": 61,
          "longitude": null,
          "latitude": null,
          "pincode": null,
          "address": null,
          "land_mark": null,
          "mobile": null,
          "name": null,
          "city_id": null,
          "state_id": null,
          "country_id": null,
          "time_slot_id": 2,
          "total_quantity": 11,
          "total_price": "152.50",
          "order_status_id": 6,
          "status": true,
          "created_at": "2021-10-07T07:38:34.000000Z",
          "updated_at": "2021-10-11T05:22:15.000000Z",
          "deleted_at": null,
          "delivery_date": "2021-10-07",
          "order_from": "mobile",
          "order_payment_status": {
            "id": 93,
            "user_id": 3,
            "order_id": 94,
            "payment_statu_id": 2,
            "token_id": null,
            "type": "COD",
            "status": true,
            "created_at": "2021-10-07T07:38:35.000000Z",
            "updated_at": "2021-10-07T07:38:35.000000Z",
            "deleted_at": null,
            "razor_payment_id": null,
            "razor_order_id": null,
            "signature": null,
            "payment_status": {
              "id": 2,
              "user_id": 1,
              "name": "Un Paid",
              "status": true,
              "created_at": "2021-08-31T20:06:46.000000Z",
              "updated_at": null,
              "deleted_at": null
            }
          },
          "time_slot": {
            "id": 2,
            "s_time": "16:00:04",
            "e_time": "20:00:17",
            "status": true,
            "created_at": "2021-08-24T19:57:53.000000Z",
            "updated_at": null,
            "deleted_at": null
          },
          "order_status": {
            "id": 6,
            "user_id": 1,
            "name": "Cancel",
            "status": true,
            "created_at": "2021-09-06T04:59:22.000000Z",
            "updated_at": "2021-09-06T04:59:22.000000Z",
            "deleted_at": null
          }
        }
      ],
      "first_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=1",
      "from": 1,
      "last_page": 2,
      "last_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=2",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": "http://192.168.10.8/vidarbha/public/api/order?page=2",
      "path": "http://192.168.10.8/vidarbha/public/api/order",
      "per_page": 10,
      "prev_page_url": null,
      "to": 10,
      "total": 18
    }
  },
  "message": "order list."
}
*/

  bool? success;
  OrderHistoryListResponseData? data;
  String? message;

  OrderHistoryListResponse({
    this.success,
    this.data,
    this.message,
  });
  OrderHistoryListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? OrderHistoryListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
