///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CartUpdateResponseDataCard {
/*
{
  "id": 1,
  "user_id": 2,
  "product_id": 1,
  "quantity": "1.00",
  "status": true,
  "created_at": "2021-08-27T09:20:26.000000Z",
  "updated_at": "2021-08-27T09:20:26.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  int? productId;
  String? quantity;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  CartUpdateResponseDataCard({
    this.id,
    this.userId,
    this.productId,
    this.quantity,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  CartUpdateResponseDataCard.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    productId = json["product_id"]?.toInt();
    quantity = json["quantity"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["product_id"] = productId;
    data["quantity"] = quantity;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class CartUpdateResponseData {
/*
{
  "card": [
    {
      "id": 1,
      "user_id": 2,
      "product_id": 1,
      "quantity": "1.00",
      "status": true,
      "created_at": "2021-08-27T09:20:26.000000Z",
      "updated_at": "2021-08-27T09:20:26.000000Z",
      "deleted_at": null
    }
  ],
  "card_id": 1
}
*/

  List<CartUpdateResponseDataCard?>? card;
  int? cardId;

  CartUpdateResponseData({
    this.card,
    this.cardId,
  });
  CartUpdateResponseData.fromJson(Map<String, dynamic> json) {
    if (json["card"] != null) {
      final v = json["card"];
      final arr0 = <CartUpdateResponseDataCard>[];
      v.forEach((v) {
        arr0.add(CartUpdateResponseDataCard.fromJson(v));
      });
      card = arr0;
    }
    cardId = json["card_id"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (card != null) {
      final v = card;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["card"] = arr0;
    }
    data["card_id"] = cardId;
    return data;
  }
}

class CartUpdateResponse {
/*
{
  "success": true,
  "data": {
    "card": [
      {
        "id": 1,
        "user_id": 2,
        "product_id": 1,
        "quantity": "1.00",
        "status": true,
        "created_at": "2021-08-27T09:20:26.000000Z",
        "updated_at": "2021-08-27T09:20:26.000000Z",
        "deleted_at": null
      }
    ],
    "card_id": 1
  },
  "message": " successfully."
}
*/

  bool? success;
  CartUpdateResponseData? data;
  String? message;

  CartUpdateResponse({
    this.success,
    this.data,
    this.message,
  });
  CartUpdateResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? CartUpdateResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["data"] = this.data!.toJson();
    data["message"] = message;
    return data;
  }
}
