///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CouponApplyResponseData {
/*
{
  "amount": "100.00"
}
*/

  String? amount;

  CouponApplyResponseData({
    this.amount,
  });
  CouponApplyResponseData.fromJson(Map<String, dynamic> json) {
    amount = json["amount"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["amount"] = amount;
    return data;
  }
}

class CouponApplyResponse {
/*
{
  "success": true,
  "data": {
    "amount": "100.00"
  },
  "message": "Cupon Code."
}
*/

  bool? success;
  CouponApplyResponseData? data;
  String? message;

  CouponApplyResponse({
    this.success,
    this.data,
    this.message,
  });
  CouponApplyResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? CouponApplyResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["data"] = this.data!.toJson();
    data["message"] = message;
    return data;
  }
}
