///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OfferListResponseDataBanner {
/*
{
  "id": 5,
  "user_id": 1,
  "type": "m_home",
  "name": "b1",
  "image": "public/admin/home/banner/Home_banner.png",
  "status": true,
  "created_at": "2021-08-26T07:50:18.000000Z",
  "updated_at": "2021-08-26T07:50:18.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? type;
  String? name;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  OfferListResponseDataBanner({
    this.id,
    this.userId,
    this.type,
    this.name,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  OfferListResponseDataBanner.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    type = json["type"]?.toString();
    name = json["name"]?.toString();
    image = json["image"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["type"] = type;
    data["name"] = name;
    data["image"] = image;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class OfferListResponseDataOffer {
/*
{
  "id": 1,
  "user_id": 1,
  "name": "vidarbha",
  "text": "vidarbha Offer Code 001",
  "image": "public/admin/offer/basket-full-vegetables (1).png",
  "status": true,
  "created_at": "2021-08-28T08:56:00.000000Z",
  "updated_at": "2021-08-28T08:56:00.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? name;
  String? text;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  OfferListResponseDataOffer({
    this.id,
    this.userId,
    this.name,
    this.text,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  OfferListResponseDataOffer.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    name = json["name"]?.toString();
    text = json["text"]?.toString();
    image = json["image"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["name"] = name;
    data["text"] = text;
    data["image"] = image;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class OfferListResponseData {
/*
{
  "offer": [
    {
      "id": 1,
      "user_id": 1,
      "name": "vidarbha",
      "text": "vidarbha Offer Code 001",
      "image": "public/admin/offer/basket-full-vegetables (1).png",
      "status": true,
      "created_at": "2021-08-28T08:56:00.000000Z",
      "updated_at": "2021-08-28T08:56:00.000000Z",
      "deleted_at": null
    }
  ],
  "banner": [
    {
      "id": 5,
      "user_id": 1,
      "type": "m_home",
      "name": "b1",
      "image": "public/admin/home/banner/Home_banner.png",
      "status": true,
      "created_at": "2021-08-26T07:50:18.000000Z",
      "updated_at": "2021-08-26T07:50:18.000000Z",
      "deleted_at": null
    }
  ]
}
*/

  List<OfferListResponseDataOffer?>? offer;
  List<OfferListResponseDataBanner?>? banner;

  OfferListResponseData({
    this.offer,
    this.banner,
  });
  OfferListResponseData.fromJson(Map<String, dynamic> json) {
    if (json["offer"] != null) {
      final v = json["offer"];
      final arr0 = <OfferListResponseDataOffer>[];
      v.forEach((v) {
        arr0.add(OfferListResponseDataOffer.fromJson(v));
      });
      offer = arr0;
    }
    if (json["banner"] != null) {
      final v = json["banner"];
      final arr0 = <OfferListResponseDataBanner>[];
      v.forEach((v) {
        arr0.add(OfferListResponseDataBanner.fromJson(v));
      });
      banner = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (offer != null) {
      final v = offer;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["offer"] = arr0;
    }
    if (banner != null) {
      final v = banner;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["banner"] = arr0;
    }
    return data;
  }
}

class OfferListResponse {
/*
{
  "success": true,
  "data": {
    "offer": [
      {
        "id": 1,
        "user_id": 1,
        "name": "vidarbha",
        "text": "vidarbha Offer Code 001",
        "image": "public/admin/offer/basket-full-vegetables (1).png",
        "status": true,
        "created_at": "2021-08-28T08:56:00.000000Z",
        "updated_at": "2021-08-28T08:56:00.000000Z",
        "deleted_at": null
      }
    ],
    "banner": [
      {
        "id": 5,
        "user_id": 1,
        "type": "m_home",
        "name": "b1",
        "image": "public/admin/home/banner/Home_banner.png",
        "status": true,
        "created_at": "2021-08-26T07:50:18.000000Z",
        "updated_at": "2021-08-26T07:50:18.000000Z",
        "deleted_at": null
      }
    ]
  },
  "message": "Offer list."
}
*/

  bool? success;
  OfferListResponseData? data;
  String? message;

  OfferListResponse({
    this.success,
    this.data,
    this.message,
  });
  OfferListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? OfferListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
